//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumClientConsole.ForumService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ForumService.IForumService", CallbackContract=typeof(ForumClientConsole.ForumService.IForumServiceCallback))]
    public interface IForumService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/AddMessage", ReplyAction="http://tempuri.org/IForumService/AddMessageResponse")]
        bool AddMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/SubscribeToForum", ReplyAction="http://tempuri.org/IForumService/SubscribeToForumResponse")]
        bool SubscribeToForum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/UnsubscribeFromForum", ReplyAction="http://tempuri.org/IForumService/UnsubscribeFromForumResponse")]
        bool UnsubscribeFromForum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetData", ReplyAction="http://tempuri.org/IForumService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IForumService/GetDataUsingDataContractResponse")]
        ForumClientCore.ForumService.CompositeType GetDataUsingDataContract(ForumClientCore.ForumService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForumServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IForumService/onUpdate")]
        void onUpdate(string message, System.DateTime timestamp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForumServiceChannel : ForumClientConsole.ForumService.IForumService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForumServiceClient : System.ServiceModel.DuplexClientBase<ForumClientConsole.ForumService.IForumService>, ForumClientConsole.ForumService.IForumService {
        
        public ForumServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ForumServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ForumServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ForumServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ForumServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool AddMessage(string message) {
            return base.Channel.AddMessage(message);
        }
        
        public bool SubscribeToForum() {
            return base.Channel.SubscribeToForum();
        }
        
        public bool UnsubscribeFromForum() {
            return base.Channel.UnsubscribeFromForum();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public ForumClientCore.ForumService.CompositeType GetDataUsingDataContract(ForumClientCore.ForumService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
